[package]
name = "novel-writing-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
console = "0.15.10"
dialoguer = "0.11.0"
serde = { version = "1.0.216", features = ["derive"] }
serde_json = "1.0.134"
